language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python pytest # or py.test for Python versytest # or py.test for Python versions 3.7 and below
